dappnode/DAppNodePackage-rocketpool-testnet

- build/ui/src/App.tsx
- build/ui/src/Dashboard.tsx
- build/ui/src/components/TopBar/ToolBar.tsx
Hide clients synced and improve the loading spinner shown when retrieving on-chain data
> Hide clients synced

- build/ui/src/components/TopBar/ToolBar.tsx
> Improved top bar style

- build/rocketpool-start.sh
- setup-wizard.yml
>  Fix #7 Set password as required

- build/ui/src/App.css
- build/ui/src/Dashboard.tsx
- build/ui/src/components/BalanceBox/BalanceBox.tsx
- build/ui/src/components/BalanceBox/CopyableAddress.tsx
- build/ui/src/components/BalanceBox/balanceBox.css
- build/ui/src/components/Buttons/BalanceButton.tsx
- build/ui/src/components/Buttons/balanceButton.css
- build/ui/src/components/Info/InfoTab.tsx
- build/ui/src/components/Rewards/RewardsTab.tsx
- build/ui/src/components/Setup/MinipoolDetails.tsx
Dashboard improved with different organization and icons
> Improve dashboard

- build/ui/src/components/Buttons/CopyToClipboardButton.tsx
- build/ui/src/components/Setup/SetupTab.tsx
- build/ui/src/components/Setup/WalletInit.tsx
- build/ui/src/components/Setup/walletInit.css
Wallet init view formatted to be prettier. Also some checks were added
> Improve wallet init view

- build/ui/src/components/Setup/CreateMinipool.tsx
- build/ui/src/components/Setup/RequiredBalanceInfo.tsx
> Fix #17 Not be aware of the Atlas flag

- build/ui/src/components/Buttons/CopyToClipboardButton.tsx
> Fix #6 Copy buttons not working on Mozilla Firefox in Linux

- build/ui/src/components/Setup/CreateMinipool.tsx
- build/ui/src/components/Setup/MinipoolEthToggle.tsx
- build/ui/src/components/Setup/RegisterNode.tsx
- build/ui/src/components/Setup/RequiredBalanceInfo.tsx
- build/ui/src/components/Setup/TxsLinksBox.tsx
- build/ui/src/components/Setup/minipool.css
- build/ui/src/components/Setup/registerNode.css
- build/ui/src/utils/Utils.ts
Improved style for register node and create minipool
Closes #21
> Improve register node UI

- build/api/src/AppConfig.ts
- build/api/src/index.ts
- build/ui/src/components/Info/InfoTab.tsx
- build/ui/src/components/Setup/CreateMinipool.tsx
- build/ui/src/services/AppService.ts
- build/ui/src/types/AppConfig.ts
- docker-compose.yml
> Fix #5 Check if the signer is active

- build/api/src/AppConfig.ts
- build/ui/src/Dashboard.tsx
- build/ui/src/components/Info/InfoTab.tsx
- build/ui/src/components/Rewards/RewardsTab.tsx
- build/ui/src/components/Setup/CreateMinipool.tsx
- build/ui/src/components/Setup/MinipoolActions.tsx
- build/ui/src/components/Setup/MinipoolCard.tsx
- build/ui/src/components/Setup/MinipoolDetails.tsx
- build/ui/src/components/Setup/RegisterNode.tsx
- build/ui/src/components/Setup/TxsLinksBox.tsx
- build/ui/src/components/Setup/WalletInit.tsx
- build/ui/src/services/AppService.ts
- build/ui/src/types/AppConfig.ts
- build/ui/src/types/RocketpoolData.ts
- build/ui/src/utils/Utils.ts
> Fix #25 Remove all static urls in UI

- build/Dockerfile
- docker-compose.yml
> Fix #26 Build UI with REACT_APP_NETWORK

- build/ui/src/components/BalanceBox/BalanceBox.tsx
- build/ui/src/components/BalanceBox/CopyableAddress.tsx
- build/ui/src/components/Info/EthClients.tsx
- build/ui/src/components/Info/InfoTab.tsx
- build/ui/src/components/Info/infoTab.css
Info view has been improved visually
> Improve Info view

- build/ui/src/components/Setup/RegisterNode.tsx
> Fix #32 Show ETH balance in blue with enough balance

- setup-wizard.yml
> Fix #34 Remove $ from password regex

- GETTING_STARTED.md
> Fix #30 Add supported clients to GETTING_STARTED

- build/rocketpool-start.sh
> Fix #38 Replace Nimbus port

- build/rocketpool-start.sh
> Fix #42 Add mainnet globals

- build/ui/src/components/Rewards/RewardsTab.tsx
> Fix #45 Claim and restake RPL taken from unclaimed intervals

- build/api/src/index.ts
- build/ui/src/App.tsx
- build/ui/src/Dashboard.tsx
- build/ui/src/components/Advanced/AdvancedTab.tsx
- build/ui/src/components/TopBar/ToolBar.tsx
- build/ui/src/components/TopBar/TopBar.tsx
- build/ui/src/services/AppService.ts
- build/ui/src/types/Tabs.ts
Advanced mode for executing commands to the rocketpool binary
> Add advanced mode

- GETTING_STARTED.md
- build/api/src/AppConfig.ts
- build/ui/src/types/AppConfig.ts
- dappnode_package.json
- docker-compose.yml
- setup-wizard.yml
Reverts dappnode/DAppNodePackage-rocketpool-testnet#63
> Revert "Apply mainnet changes"

- build/ui/src/components/Advanced/AdvancedTab.tsx
- build/ui/src/utils/Utils.ts
> Fix #68 Escape \n in Advanced mode output

- build/api/src/AppConfig.ts
- build/api/src/index.ts
- build/rocketpool-start.sh
- build/ui/src/components/Setup/RequiredBalanceInfo.tsx
- build/ui/src/types/AppConfig.ts
- build/ui/src/types/Network.ts
- dappnode_package.json
- docker-compose.yml
> Fix #93 Replace prater by holesky

- build/Dockerfile
Necessary for v1.13.0 (Go updated)
> Update node to v20.12.2 in Dockerfile

- build/ui/src/components/Setup/RegisterNode.tsx
> Fix #106 Revoke the requirement to have enough tokens to register the node
